export const Bakgrounds = ["Background",
    "Avocado","Black Purple","Blue Ball","Blue Biege","Blue Fish","Blue Green","Blue Red","BubbleGum","Burnt Orange","Celadon","Dark Blue","Dragon Moon","Dragon","Dusty Grey","Dusty Orange","Fish & Sun","Flame","Flamed Skinned","Flower","Glowing Orange","Gold","Green White","Kamifusen Flower","Kamifusen","Lime Yellow","Lime","Marron White","Maru","Moss","Mountain Red","Mountain View","Mulberry","Orange Maru","Orange White","Puce","Purple Gradient","Purple Yellow","Purple","Red Masuku","Red White","Red Yellow","RGB Lights","Salmon","Samurai Bushi","Samurai Tone","Skined Carpet","Skined Leaves","Skined Pink Carpet","Skinned Green Yellow","Skinned Maru","Storm Mix","Sun Bushi"
  ]
  export const Masks = ["Mask","Kitsune","Jig Saw","Casa De Papel","Upset Kitsune"]
  export const Eyes = ["Eyes", "Blue","Green Pink","Normal","Purple Diamond","Purple","Red"]
  export const Glass = ["Glass","Blue Aviator","Cat Eye","Half Rim","Half Round","Heart","Mirrored","Oval","Red Aviator","Shield","Shutter Shade","Wayfarer"]
  export const Hair = ["Hair","Aqua","Blond Punk","Blond Small Bun","Blunt Bangs Green","Blunt Bangs Pink","Brown Double Buns","Brown Small Bun","Classic Bob Brown","Emo Green","Geisha","Long Straight","Straigth Medium"]

  export const Clothing = ["Clothing",
      "Beige Gorset","Black Bikini","Black Lace Dress","Blue Brick Gorset","Blue Gorset","Blue Sky TankTop","Burberry Veste","Capri TankTop","Carpet Veste","Charm TankTop","Cherry TankTop","Cream TankTop","Cyan TankTop","Dark School Dress","School Dress","Flamengo TankTop","Flory TankTop","Flower Bikini","Flower TankTop","Flower Veste","Flowered Kimono","Flowered Tshirt","Goku","Gradient Pink Tshirt","Gray Oversisezd Pull","Gray Printed Tshirt","Gray TankTop","Gray Tshirt","Green Gradient Tshirt","Jill Valentine","Khaki Bikini","Kimono Skinned","Kimono","Kitten Tshirt","Light Orange TankTop","Light Panther Veste","Love Bikini","Love TankTop","Military","Mixed Colors Gorset","Neutral Gorset","Orange Gorset","Orange School Dress","Oversisezd Pull","Panther Bikini","Panther Veste","Pink Bikini","Pink Kimono","Police","Purplr Tshirt","Red Bikini","Red Kimono","Red Tshirt","Seafoom Bikini","Silver TankTop","Skin Orange Tshirt","Sky TankTop","Snake Veste","Striped Bikini","SunLight TankTop","Sunset Bikini","Sweater","Turtle TankTop","Vetse","White Kimono","White Lace Dress","White TankTop","White Tshirt","Yellow Gorset","Yellow Kimono"
    ]
  export const Hand = ["Hand",
      "Avocado Juice","Beer","Chain","Cig & Soda","Ciguarette","Coffee & Ciguarette","Coffee","Deser Eagle","Desert Eagle Colored & Katana","desert eagle colored","desert eagle flowers","desert eagle gold","desert eagle gray","desert eagle orange","desert eagle painted","Hashi","Hitman Colored","Hitman Gold","Katana","Lolipop & Katana","Lolipop","Magnum  Gecko","Magnum  Snake","Magnum 44","Magnum Black & Gold","Magnum Black & Orange","Magnum Blue & Gray","Magnum Gold Carpet","Magnum Gold","Magnum Gray Flowers","Magnum Gray","Magnum Green Black","Magnum Light Gray Skin","Magnum Painted","Magnum Tortule","Magnum Zebra","Orange Juice","Phone & Chain","Phone & Desert Eagle","Phone & Katana","Phone & Wine","Phone","Rice & Hashi","Rice","Soda","Wine"
    ]