export const CryptoPlaceholder = [
    { 
        "uuid": "Qwsogvtv82FCd",
        "rank":'1',
        "symbol": "BTC",
        "name": "Bitcoin",
        "color": "#f7931A",
        "iconUrl": "https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg",
        "marketCap": "522526803958",
        "price": "27187.09642019748",
        "listedAt": 1330214400,
        "tier": 1,
        "change": "0.90",
        "rank": 1,
        "lowVolume": false,
        "coinrankingUrl": "https://coinranking.com/coin/Qwsogvtv82FCd+bitcoin-btc",
        "24hVolume": "61256458171",
        "btcPrice": "1",
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":["quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione" ,'bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
        

    },
    {
        "uuid": "razxDUgYGNAdQ",
        "symbol": "ETH",
        "name": "Ethereum",
        "color": "#3C3C3D",
        "iconUrl": "https://cdn.coinranking.com/rk4RKHOuW/eth.svg",
        "marketCap": "225945321969",
        "price": "1851.38983657688",
        "listedAt": 1438905600,
        "tier": 1,
        "change": "1.45",
        "rank": 2,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "HIVsRcGKkPFtW",
        "symbol": "USDT",
        "name": "Tether USD",
        "color": "#22a079",
        "iconUrl": "https://cdn.coinranking.com/mgHqwlCLj/usdt.svg",
        "marketCap": "65493145453",
        "price": "1.001996008235732",
        "listedAt": 1420761600,
        "tier": 1,
        "change": "-0.33",
        "rank": 3,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "WcwrkfNI4FUAe",
        "symbol": "BNB",
        "name": "BNB",
        "color": "#e8b342",
        "iconUrl": "https://cdn.coinranking.com/B1N19L_dZ/bnb.svg",
        "marketCap": "44757039459",
        "price": "313.39073058979545",
        "listedAt": 1503014400,
        "tier": 1,
        "change": "0.81",
        "rank": 4,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',    },
    {
        "uuid": "aKzUVe4Hh_CON",
        "symbol": "USDC",
        "name": "USDC",
        "color": "#7894b4",
        "iconUrl": "https://cdn.coinranking.com/jkDf8sQbY/usdc.svg",
        "marketCap": "43831273492",
        "price": "1.0012174586910139",
        "listedAt": 1539043200,
        "tier": 1,
        "change": "-0.28",
        "rank": 5,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "-l8Mn2pVlRs-p",
        "symbol": "XRP",
        "name": "XRP",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/B1oPuTyfX/xrp.svg",
        "marketCap": "23271919157",
        "price": "0.46267403932716283",
        "listedAt": 1421798400,
        "tier": 1,
        "change": "-0.43",
        "rank": 6,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "qzawljRxB5bYu",
        "symbol": "ADA",
        "name": "Cardano",
        "color": "#3cc8c8",
        "iconUrl": "https://cdn.coinranking.com/ryY28nXhW/ada.svg",
        "marketCap": "12957805896",
        "price": "0.36974741601846095",
        "listedAt": 1506902400,
        "tier": 1,
        "change": "0.43",
        "rank": 7,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "a91GCGd_u96cF",
        "symbol": "DOGE",
        "name": "Dogecoin",
        "color": "#c2a633",
        "iconUrl": "https://cdn.coinranking.com/H1arXIuOZ/doge.svg",
        "marketCap": "9962660853",
        "price": "0.07280637920477293",
        "listedAt": 1391212800,
        "tier": 1,
        "change": "-0.54",
        "rank": 8,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k' , "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "uW2tk-ILY0ii",
        "symbol": "MATIC",
        "name": "Polygon",
        "color": "#8247e5",
        "iconUrl": "https://cdn.coinranking.com/M-pwilaq-/polygon-matic-logo.svg",
        "marketCap": "8221577261",
        "price": "0.8870244722988311",
        "listedAt": 1558961160,
        "tier": 1,
        "change": "1.37",
        "rank": 9,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "qUhEFk1I61atv",
        "symbol": "TRX",
        "name": "TRON",
        "color": "#eb0029",
        "iconUrl": "https://cdn.coinranking.com/behejNqQs/trx.svg",
        "marketCap": "7253351810",
        "price": "0.07871376998655165",
        "listedAt": 1505260800,
        "tier": 1,
        "change": "-0.24",
        "rank": 10,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "zNZHO_Sjf",
        "symbol": "SOL",
        "name": "Solana",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/yvUG4Qex5/solana.svg",
        "marketCap": "7249437094",
        "price": "19.96224631672792",
        "listedAt": 1586539320,
        "tier": 1,
        "change": "1.85",
        "rank": 11,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "Mtfb0obXVh59u",
        "symbol": "WETH",
        "name": "Wrapped Ether",
        "color": "#303030",
        "iconUrl": "https://cdn.coinranking.com/KIviQyZlt/weth.svg",
        "marketCap": "6727014965",
        "price": "1821.9561243056992",
        "listedAt": 1600259445,
        "tier": 1,
        "change": "0.95",
        "rank": 12,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',   },
    {
        "uuid": "25W7FG7om",
        "symbol": "DOT",
        "name": "Polkadot",
        "color": "#d64cA8",
        "iconUrl": "https://cdn.coinranking.com/RsljYqnbu/polkadot.svg",
        "marketCap": "6631904972",
        "price": "5.391289549358539",
        "listedAt": 1598365200,
        "tier": 1,
        "change": "1.16",
        "rank": 13,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "D7B1x_ks7WhV5",
        "symbol": "LTC",
        "name": "Litecoin",
        "color": "#345d9d",
        "iconUrl": "https://cdn.coinranking.com/BUvPxmc9o/ltcnew.svg",
        "marketCap": "6507295283",
        "price": "91.82624679381706",
        "listedAt": 1382572800,
        "tier": 1,
        "change": "0.73",
        "rank": 14,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "VLqpJwogdhHNb",
        "symbol": "LINK",
        "name": "Chainlink",
        "color": "#4680b0",
        "iconUrl": "https://cdn.coinranking.com/9NOP9tOem/chainlink.svg",
        "marketCap": "6496857584",
        "price": "6.497445766517693",
        "listedAt": 1505952000,
        "tier": 1,
        "change": "-0.55",
        "rank": 15,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "vSo2fu9iE1s0Y",
        "symbol": "BUSD",
        "name": "Binance USD",
        "color": "#f0b90b",
        "iconUrl": "https://cdn.coinranking.com/6SJHRfClq/busd.svg",
        "marketCap": "5409839570",
        "price": "1.001716025513866",
        "listedAt": 1563197940,
        "tier": 1,
        "change": "-0.41",
        "rank": 16,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },

    {
        "uuid": "xz24e0BjL",
        "symbol": "SHIB",
        "name": "Shiba Inu",
        "color": "#fda32b",
        "iconUrl": "https://cdn.coinranking.com/fiZ4HfnRR/shib.png",
        "marketCap": "5235167342",
        "price": "0.000008880182799156",
        "listedAt": 1620650373,
        "tier": 1,
        "change": "0.13",
        "rank": 17,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',},
    {
        "uuid": "MoTuySvg7",
        "symbol": "DAI",
        "name": "Dai",
        "color": "#ea9999",
        "iconUrl": "https://cdn.coinranking.com/mAZ_7LwOE/mutli-collateral-dai.svg",
        "marketCap": "4776210003",
        "price": "1.001186480863921",
        "listedAt": 1585574040,
        "tier": 1,
        "change": "-0.10",
        "rank": 18,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "x4WXHge-vvFY",
        "symbol": "WBTC",
        "name": "Wrapped BTC",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/o3-8cvCHu/wbtc[1].svg",
        "marketCap": "4417086688",
        "price": "27219.19112395121",
        "listedAt": 1549894980,
        "tier": 1,
        "change": "0.91",
        "rank": 19,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',  },
    {
        "uuid": "dvUj0CzDZ",
        "symbol": "AVAX",
        "name": "Avalanche",
        "color": "#e84242",
        "iconUrl": "https://cdn.coinranking.com/S0C6Cw2-w/avax-avalanche.png",
        "marketCap": "4412716301",
        "price": "14.673785732272325",
        "listedAt": 1600961596,
        "tier": 1,
        "change": "-0.34",
        "rank": 20,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',    },
    {
        "uuid": "_H5FVG9iW",
        "symbol": "UNI",
        "name": "Uniswap",
        "color": "#ff007a",
        "iconUrl": "https://cdn.coinranking.com/1heSvUgtl/uniswap-v2.svg?size=48x48",
        "marketCap": "4065648092",
        "price": "5.060972387529918",
        "listedAt": 1600323371,
        "tier": 1,
        "change": "-0.57",
        "rank": 21,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "CiixT63n3",
        "symbol": "WSTETH",
        "name": "Wrapped liquid staked Ether 2.0",
        "color": "#70b9dc",
        "iconUrl": "https://cdn.coinranking.com/LQg69oxqx/wstETH.PNG",
        "marketCap": "3513526021",
        "price": "2062.654523082471",
        "listedAt": 1638756833,
        "tier": 1,
        "change": "3.10",
        "rank": 22,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',    },
    {
        "uuid": "Knsels4_Ol-Ny",
        "symbol": "ATOM",
        "name": "Cosmos",
        "color": "#5064fb",
        "iconUrl": "https://cdn.coinranking.com/HJzHboruM/atom.svg",
        "marketCap": "3460646085",
        "price": "10.515564101456375",
        "listedAt": 1552520100,
        "tier": 1,
        "change": "0.05",
        "rank": 23,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "67YlI0K1b",
        "symbol": "TON",
        "name": "Toncoin",
        "color": "#0088cc",
        "iconUrl": "https://cdn.coinranking.com/1mf2KPPah/toncoin.png",
        "marketCap": "2992444247",
        "price": "2.0307150443361364",
        "listedAt": 1640268459,
        "tier": 1,
        "change": "10.37",
        "rank": 24,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "3mVx2FX_iJFp5",
        "symbol": "XMR",
        "name": "Monero",
        "color": "#ff7519",
        "iconUrl": "https://cdn.coinranking.com/Syz-oSd_Z/xmr.svg",
        "marketCap": "2766376884",
        "price": "151.94192404340444",
        "listedAt": 1422489600,
        "tier": 1,
        "change": "-0.20",
        "rank": 25,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "hnfQfsYfeIGUQ",
        "symbol": "ETC",
        "name": "Ethereum Classic",
        "color": "#699070",
        "iconUrl": "https://cdn.coinranking.com/rJfyor__W/etc.svg",
        "marketCap": "2544086871",
        "price": "18.410511355425328",
        "listedAt": 1469577600,
        "tier": 1,
        "change": "0.29",
        "rank": 26,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "Pe93bIOD2",
        "symbol": "LDO",
        "name": "Lido DAO Token",
        "color": "#77cced",
        "iconUrl": "https://cdn.coinranking.com/Wp6LFY6ZZ/8000.png",
        "marketCap": "2377369341",
        "price": "2.032195401646608",
        "listedAt": 1627361901,
        "tier": 1,
        "change": "0.75",
        "rank": 27,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "ZlZpzOJo43mIo",
        "symbol": "BCH",
        "name": "Bitcoin Cash",
        "color": "#8dc451",
        "iconUrl": "https://cdn.coinranking.com/By8ziihX7/bch.svg",
        "marketCap": "2213182069",
        "price": "115.68322658790566",
        "listedAt": 1541808000,
        "tier": 1,
        "change": "0.13",
        "rank": 28,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "aMNLwaUbY",
        "symbol": "ICP",
        "name": "Internet Computer (DFINITY)",
        "color": "#00042b",
        "iconUrl": "https://cdn.coinranking.com/1uJ_RVrmC/dfinity-icp.png",
        "marketCap": "2191065599",
        "price": "5.0214472533032835",
        "listedAt": 1601555742,
        "tier": 1,
        "change": "-1.15",
        "rank": 29,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "f3iaFeCKEmkaZ",
        "symbol": "XLM",
        "name": "Stellar",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/78CxK1xsp/Stellar_symbol_black_RGB.svg",
        "marketCap": "1787649523",
        "price": "0.08847330863629985",
        "listedAt": 1484611200,
        "tier": 1,
        "change": "-0.08",
        "rank": 30,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "DXwP4wF9ksbBO",
        "symbol": "HT",
        "name": "Huobi Token",
        "color": "#2daadf",
        "iconUrl": "https://cdn.coinranking.com/ryFpQe0c7/ht.svg",
        "marketCap": "1576874541",
        "price": "3.1537490955571053",
        "listedAt": 1517702400,
        "tier": 1,
        "change": "6.40",
        "rank": 31,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "Z96jIvLU7",
        "symbol": "IMX",
        "name": "Immutable X",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/naRGT2Y_X/10603.png",
        "marketCap": "1533207193",
        "price": "0.7666035978299338",
        "listedAt": 1649387294,
        "tier": 1,
        "change": "5.02",
        "rank": 32,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "ymQub4fuB",
        "symbol": "FIL",
        "name": "Filecoin",
        "color": "#0090ff",
        "iconUrl": "https://cdn.coinranking.com/vUmvv-IQA/FIL3-filecoin.svg?size=48x48",
        "marketCap": "1479556961",
        "price": "4.519495726377735",
        "listedAt": 1602839473,
        "tier": 1,
        "change": "2.13",
        "rank": 33,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',    },
    {
        "uuid": "1Uo6s62Oc",
        "symbol": "ARB",
        "name": "ARBITRUM",
        "color": "#9fc5e8",
        "iconUrl": "https://cdn.coinranking.com/hUTOnQLcU/ARBITRUM_LOGO.png",
        "marketCap": "1470827028",
        "price": "1.1535898258465045",
        "listedAt": 1679022695,
        "tier": 1,
        "change": "2.45",
        "rank": 34,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "7C4Mh4xy1yDel",
        "symbol": "RNDR",
        "name": "Render Token",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/lhbmnCedl/5690.png",
        "marketCap": "1462628675",
        "price": "2.7453504131258906",
        "listedAt": 1562331120,
        "tier": 1,
        "change": "13.20",
        "rank": 35,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "Hm3OlynlC",
        "symbol": "TWT",
        "name": "Trust Wallet Token",
        "color": "#3375bb",
        "iconUrl": "https://cdn.coinranking.com/cZ5j4jiOk/trust-wallet-token.svg",
        "marketCap": "1338406152",
        "price": "1.1024779295763274",
        "listedAt": 1610717385,
        "tier": 1,
        "change": "2.86",
        "rank": 36,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "FEbS54wxo4oIl",
        "symbol": "VET",
        "name": "VeChain",
        "color": "#4bc0fa",
        "iconUrl": "https://cdn.coinranking.com/B1_TDu9Dm/VEN.svg",
        "marketCap": "1293536895",
        "price": "0.019375711980072607",
        "listedAt": 1533427200,
        "tier": 1,
        "change": "0.00",
        "rank": 37,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply', },
    {
        "uuid": "jad286TjB",
        "symbol": "HBAR",
        "name": "Hedera",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/dSCnSLilQ/hedera.svg",
        "marketCap": "1288281225",
        "price": "0.052076545572533016",
        "listedAt": 1568704980,
        "tier": 1,
        "change": "-0.48",
        "rank": 38,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "QUC5kVAxSoB-",
        "symbol": "MX",
        "name": "MX Token",
        "color": null,
        "iconUrl": "https://cdn.coinranking.com/5H4rM81Pj/mxc.svg",
        "marketCap": "1287299027",
        "price": "2.958731202724055",
        "listedAt": 1568732160,
        "tier": 1,
        "change": "0.23",
        "rank": 39,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',    },
    {
        "uuid": "3nNpuxHJ8",
        "symbol": "FXS",
        "name": "Frax Share",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/_UuWZ5htj/FS.png",
        "marketCap": "1230592324",
        "price": "7.002409661097517",
        "listedAt": 1640985232,
        "tier": 1,
        "change": "0.45",
        "rank": 40,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "pxtKbG5rg",
        "symbol": "SAND",
        "name": "The Sandbox",
        "color": "#00adef",
        "iconUrl": "https://cdn.coinranking.com/kd_vwOcnI/sandbox.png",
        "marketCap": "1204835283",
        "price": "0.5061747001799011",
        "listedAt": 1613583024,
        "tier": 1,
        "change": "-1.10",
        "rank": 41,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "TpHE2IShQw-sJ",
        "symbol": "ALGO",
        "name": "Algorand",
        "color": null,
        "iconUrl": "https://cdn.coinranking.com/lzbmCkUGB/algo.svg",
        "marketCap": "1173481864",
        "price": "0.162065958464224",
        "listedAt": 1562082540,
        "tier": 1,
        "change": "-0.04",
        "rank": 42,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "HGYj5JCv5",
        "symbol": "APT",
        "name": "Aptos",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/KXUaDFjqm/21794.png",
        "marketCap": "1096595482",
        "price": "8.43534986181196",
        "listedAt": 1666148370,
        "tier": 1,
        "change": "4.39",
        "rank": 43,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
                "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "tEf7-dnwV3BXS",
        "symbol": "MANA",
        "name": "Decentraland",
        "color": "#f47e33",
        "iconUrl": "https://cdn.coinranking.com/ph_svUzXs/decentraland(1).svg",
        "marketCap": "1043990758",
        "price": "0.4760170519867112",
        "listedAt": 1500336000,
        "tier": 1,
        "change": "-0.64",
        "rank": 44,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"false",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "SbWqqTui-",
        "symbol": "ENS",
        "name": "EnergySwap",
        "color": "#ffda55",
        "iconUrl": "https://cdn.coinranking.com/fmYxEUV5a/cropped-logo37-Converted-01-192x192.png",
        "marketCap": "1034827670",
        "price": "10.348276704219087",
        "listedAt": 1626134763,
        "tier": 1,
        "change": "2.43",
        "rank": 45,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"dals",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "JCKLgWPAF",
        "symbol": "USDP",
        "name": "Pax Dollar",
        "color": "#2ac27a",
        "iconUrl": "https://cdn.coinranking.com/KUd2bJXdn/3330.png",
        "marketCap": "1016725932",
        "price": "1.000765999227235",
        "listedAt": 1650960626,
        "tier": 1,
        "change": "-0.33",
        "rank": 46,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "bauj_21eYVwso",
        "symbol": "QNT",
        "name": "Quant",
        "color": "#585e63",
        "iconUrl": "https://cdn.coinranking.com/a-i9Dl392/quant.png",
        "marketCap": "1000497977",
        "price": "102.32932668604028",
        "listedAt": 1533945600,
        "tier": 1,
        "change": "0.84",
        "rank": 47,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "DCrsaMv68",
        "symbol": "NEAR",
        "name": "NEAR Protocol",
        "color": "#000000",
        "iconUrl": "https://cdn.coinranking.com/Cth83dCnl/near.png",
        "marketCap": "995277093",
        "price": "1.6373881285567167",
        "listedAt": 1615164591,
        "tier": 1,
        "change": "1.60",
        "rank": 48,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":false,
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "65PHZTpmE55b",
        "symbol": "CRO",
        "name": "Cronos",
        "color": "#01275d",
        "iconUrl": "https://cdn.coinranking.com/2o91jm73M/cro.svg",
        "marketCap": "970248868",
        "price": "0.06196986464406939",
        "listedAt": 1548953220,
        "tier": 1,
        "change": "-0.04",
        "rank": 49,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
    },
    {
        "uuid": "ixgUfzmLR",
        "symbol": "AAVE",
        "name": "Aave",
        "color": "#B6509E",
        "iconUrl": "https://cdn.coinranking.com/4bpYKqV4X/AAVE.png",
        "marketCap": "948894379",
        "price": "65.36130248996021",
        "listedAt": 1603447311,
        "tier": 1,
        "change": "1.68",
        "rank": 50,
        "link":'pinksale/presale',
        "platform":'pinksale',
        "startTime":'10/20/2023',
        "endTime":'15/10/2023',
        "link":'/no fairlaunch "link"',
        "platform":'no fairlaunch "platform"',
        "startTime":'no start time',
        "endTime":'no end time',
        "twitter":'https://"twitter".com',
        "github":'https://"github".com',
        "telegram":'https://"telegram".com',
        "youtube":'https://"youtube".com',
        "facebook":'https://"facebook".com',
        "instagram":'https://"instagram".com',
        "isTrusted":"true",
        "isAudited":"true",
        "isKyc":"true",
        "isPromoted":"true",
        "bannerLink":'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
        "isNew":'true',
        "numOfLikes":'5006',
        "numOfdislikes":'150',
        "comments":['bitcoin to the moon! ', 'pump!!', 'i bought 10k'],
        "reports":'0',
        "addedBy":'',
        "contractAaddress":'0x4B04213C2774f77e60702880654206B116D00508',
        "network":'BTC',
        "audit":"true",
        "Kyc":"true",
        "doxx":"true",
        "supply":'1565648 total supply',
      
    }
]