

export const PRODUCTS = [
  {
    id: 1,
    name: "zombie Pepe",
    description: "Brown cockroach wings",
    price: 74,
    image: "https://nypost.com/wp-content/uploads/sites/2/2021/06/sized-coinbase.jpg?quality=75&strip=all&w=744",
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
   
    variantType: "image",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    status: "New in",
  },
  {
    id: 2,
    name: 'Binance Coin',
    description: "Classic green",
    price: 68,
    image: "https://crypto.news/app/uploads/2022/01/cn-service-binance.png",
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
    
    variantType: "color",
    status: "50% Discount",
  },
  {
    id: 3,
    name: "Bitcoin",
    description: "New blue aqua",
    price: 132,
    image: 'https://www.analyticsinsight.net/wp-content/uploads/2021/05/Cryptocurrency-Market.jpg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
   
    variantType: "image",
    sizes: ["S", "M", "L", "XL"],
    allOfSizes: ["S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 4,
    name: "TSand Box",
    description: "Dark pink 2023",
    price: 28,
    image: "https://c8.alamy.com/comp/2H0X9P2/binance-logo-on-the-background-of-the-trading-terminal-binancecom-2H0X9P2.jpg",
    category: "Category 1",
    tags: ["tag1", "tag2"],
    
    variantType: "color",
    link: "/product-detail/",
    status: "Sold Out",
  },
  {
    id: 5,
    name: "XRP",
    description: "Perfect mint green",
    price: 42,
    image: 'https://cryptopotato.com/wp-content/uploads/2021/12/Dogecoin.jpg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
   
    variantType: "image",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    link: "/product-detail/",
  },
  {
    id: 6,
    name: "Doge Coin",
    description: "New design 2023",
    price: 30,
    image: 'https://www.cryptotimes.io/wp-content/uploads/2023/05/pepe_coin_article.jpg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    variantType: "color",
    
    link: "/product-detail/",
  },
  {
    id: 7,
    name: "LiteCoin",
    description: "Matte black",
    price: 12,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfamobVRoglRHyuxoATxAe2Shq8U0Cvw3ZWy7g3ohm3OHjVce1Y6IQI2-qcATmIdOetM8&usqp=CAU',
    category: "Category 1",
    tags: ["tag1", "tag2"],
   
    variantType: "image",
    link: "/product-detail/",
    status: "New in",
  },
  {
    id: 8,
    name: "Shitcoin",
    description: "Cream pink",
    price: 145,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfamobVRoglRHyuxoATxAe2Shq8U0Cvw3ZWy7g3ohm3OHjVce1Y6IQI2-qcATmIdOetM8&usqp=CAU",
    category: "Category 1",
    tags: ["tag1", "tag2"],
   
    variantType: "image",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    link: "/product-detail/",
    status: "limited edition",
  },
];

export const SPORT_PRODUCTS = [
  {
    id: 1,
    name: "Shiba Inu",
    description: "Brown cockroach wings",
    price: 74,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfamobVRoglRHyuxoATxAe2Shq8U0Cvw3ZWy7g3ohm3OHjVce1Y6IQI2-qcATmIdOetM8&usqp=CAU",
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
    
    variantType: "color",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    status: "New in",
  },
  {
    id: 2,
    name: "SafeMoon",
    description: "Classic green",
    price: 68,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfamobVRoglRHyuxoATxAe2Shq8U0Cvw3ZWy7g3ohm3OHjVce1Y6IQI2-qcATmIdOetM8&usqp=CAU',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
    
    variantType: "color",
    status: "50% Discount",
  },
  {
    id: 3,
    name: "SafeMars",
    description: "New blue aqua",
    price: 132,
    image: 'https://play-lh.googleusercontent.com/ACgOvt6MNsYoCZCsYFMsU1E_1wojlcw71xDcx46fQV6BAvMAl1S5KN5wcAYNCs4sfg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    link: "/product-detail/",
   
    variantType: "image",
    sizes: ["S", "M", "L", "XL"],
    allOfSizes: ["S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 4,
    name: "RedElon Musk",
    description: "Dark pink 2023",
    price: 28,
    image: 'https://play-lh.googleusercontent.com/ACgOvt6MNsYoCZCsYFMsU1E_1wojlcw71xDcx46fQV6BAvMAl1S5KN5wcAYNCs4sfg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    
    variantType: "color",
    link: "/product-detail/",
    status: "Sold Out",
  },
  {
    id: 5,
    name: "Doge Coin inu",
    description: "Perfect mint green",
    price: 42,
    image: '',
    category: "Category 1",
    tags: ["tag1", "tag2"],
   
    variantType: "image",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    link: "/product-detail/",
  },
  {
    id: 6,
    name: "Saytama",
    description: "New design 2023",
    price: 30,
    image: 'https://cryptopotato.com/wp-content/uploads/2021/12/Dogecoin.jpg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    variantType: "color",
    
    link: "/product-detail/",
  },
  {
    id: 7,
    name: "Bubble butt ",
    description: "Matte black",
    price: 12,
    image: 'https://d1e00ek4ebabms.cloudfront.net/production/5b6adf89-45c7-46ea-a466-fe8616f32b16.jpg',
    category: "Category 1",
    tags: ["tag1", "tag2"],
   
    variantType: "image",
    link: "/product-detail/",
    status: "New in",
  },
  {
    id: 8,
    name: "red hot chille pepers",
    description: "Cream pink",
    price: 145,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfjN4LdGRL6k0z-6vh2RS7MjIBo4167zc6d6LXESrRbVvaeX1CGuPqDnLQ2HDQeGdEOlg&usqp=CAU',
    category: "Category 1",
    tags: ["tag1", "tag2"],
    
    variantType: "color",
    sizes: ["XS", "S", "M", "L", "XL"],
    allOfSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    link: "/product-detail/",
    status: "limited edition",
  },
];
